{% set version="1.3.3.20190515200948" %}

package:
  name: arvados-python-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arvados-python-client/arvados-python-client-{{ version }}.tar.gz
  sha256: 76ba4659f648358fe22db96d8b6f11203451cfe9d98df6a5a314de4fe9a66816

build:
  skip: true  # [osx]
  number: 0
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - ciso8601 >=2.0.0
    - future
    - google-api-python-client <1.7,>=1.6.2
    - httplib2
    - pycurl >=7.19.5.1
    - ruamel.yaml >=0.15.54
    - ws4py >=0.4.2
    - subprocess32  # [py2k]

  run:
    - python
    - setuptools
    - ciso8601 >=2.0.0
    - future
    - google-api-python-client <1.7,>=1.6.2
    - httplib2
    - pycurl >=7.19.5.1
    - ruamel.yaml >=0.15.54
    - ws4py >=0.4.2
    - subprocess32  # [py2k]

test:
  imports:
    - arvados

about:
  home: https://github.com/curoverse/arvados/tree/master/sdk/python
  license: Apache License 2.0
  summary: Python API for Arvados, an open source platform for managing and analyzing biomedical big data

extra:
  skip-lints:
    - uses_setuptools

