{% set name = "epic2" %}
{% set version = "0.0.36" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "34e116d3fa0de387d6e973cc45d700c5297b51147f71ed09e5ed2e13ee8478d6" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build: 
  number: 0
  skip: 
    True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - setuptools
    - scipy
    - numpy
    - pysam
    - natsort
    - functools32  # [py27]
    - htslib
    - libdeflate
  run:
    - python
    - scipy
    - numpy
    - pysam
    - natsort
    - functools32 # [py27]
    - htslib
    - libdeflate


test:
  # Python imports
  imports:
    - epic2
  commands:
    - epic2 -h

about:
  home: http://github.com/endrebak/epic2
  license: MIT
  summary: 'Ultraperformant Chip-Seq broad domain finder based on SICER.'
